# -*- coding: utf-8 -*-
"""modeling_case_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBjTNov7up602TfY-77ilzcgFHAVgE63
"""

!pip install Sastrawi emoji

import pandas as pd
import numpy as np
import json
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import emoji



file_path = "data_untuk_modeling.csv"

"""#### Preprocessing Text"""

df = pd.read_csv(file_path)
df.columns.tolist()

# mengecek kolom kosong
df.isnull().sum()

df.head(3)

df['text_gabungan'] = (
    # "judul: " + df['Judul'].fillna('') + " " +
    "industri: " + df['Industri'].fillna('') + " " +
    "kategori: " + df['Kategori'].fillna('') + " " +
    "pendidikan: " + df['Pendidikan'].fillna('') + " " +
    "tipe: " + df['Tipe'].fillna('') + " " +
    "lokasi: " + (df['Kota'].fillna('') + " " + df['Provinsi'].fillna('')) + " " +
    "skills: " + df['Skills'].fillna('') + " " +
    "deskripsi: " + df['Deskripsi'].fillna('')
)

print(df['text_gabungan'][0])

"""##### Cleaning"""

def basic_clean(text):
    text = text.lower()
    text = re.sub(r'<.*?>', ' ', text)                 # HTML
    text = re.sub(r'[^a-z0-9\s:/_\-\+\.]', ' ', text) # keep tanda penting
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['text_gabungan'] = df['text_gabungan'].apply(basic_clean)
print(df['text_gabungan'][0])

"""##### Case Folding"""

def case_folding(text):
    text = text.lower()
    return text

df["text_gabungan"] = df["text_gabungan"].apply(case_folding)
print(df["text_gabungan"][1])

"""##### Normalization"""

# df_normalisasi = pd.read_csv("colloquial-indonesian-lexicon-normalisasi.csv")
# df_normalisasi = df_normalisasi[["slang", "formal"]]
# df_normalisasi.head()

# normalization_dict = dict(zip(df_normalisasi['slang'], df_normalisasi['formal']))
# normalization_dict.pop('it')

# def normalization(text):
#     words = text.split()
#     words = [normalization_dict.get(word, word) for word in words]
#     return ' '.join(words)

# df['text_gabungan'] = df["text_gabungan"].apply(normalization)
# print(df['text_gabungan'][1])

"""##### Stopword Removal"""

# tidak relevan untuk kasus INDO ENGLISH, karena banyak kata yang sudah baku dan tidak ada slang yang perlu dinormalisasi dan Stopword

"""#### Membangun Modeling dengan Pseudo-CV

#### Membangun Data Pseudo-CV
"""

df['pseudo_cv'] = (
    # "judul: " + df['Judul'].fillna('') + " " +
    "industri: " + df['Industri'].fillna('') + " " +
    "kategori: " + df['Kategori'].fillna('') + " " +
    "pendidikan: " + df['Pendidikan'].fillna('') + " " +
    "tipe: " + df['Tipe'].fillna('') + " " +
    "skills: " + df['Skills'].fillna('') + " "
)
print(df['pseudo_cv'][0])

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Menghitung jumlah kata (panjang sequence) untuk setiap baris di text_gabungan
# Pastikan teks sudah melalui tahap basic_clean / case_folding
df['seq_length'] = df['text_gabungan'].apply(lambda x: len(str(x).split()))

# 2. Menghitung statistik deskriptif dan persentil
panjang_rata2 = df['seq_length'].mean()
persentil_80 = np.percentile(df['seq_length'], 80)
persentil_90 = np.percentile(df['seq_length'], 90)
persentil_95 = np.percentile(df['seq_length'], 95)
max_length = df['seq_length'].max()

print(f"Rata-rata panjang kata : {panjang_rata2:.0f} kata")
print(f"80% data berada di bawah: {persentil_80:.0f} kata")
print(f"90% data berada di bawah: {persentil_90:.0f} kata")
print(f"95% data berada di bawah: {persentil_95:.0f} kata")
print(f"Panjang kata maksimum  : {max_length} kata")

# 3. Membuat Plot Distribusi
plt.figure(figsize=(12, 6))
sns.histplot(df['seq_length'], bins=50, kde=True, color='#2c7bb6')

# Menambahkan garis vertikal untuk persentil sebagai panduan penentuan MAX_LEN
plt.axvline(panjang_rata2, color='green', linestyle='-', linewidth=2, label=f'Rata-rata ({panjang_rata2:.0f})')
plt.axvline(persentil_90, color='red', linestyle='--', linewidth=2, label=f'90th Percentile ({persentil_90:.0f})')
plt.axvline(persentil_95, color='orange', linestyle='--', linewidth=2, label=f'95th Percentile ({persentil_95:.0f})')

# Kustomisasi tampilan plot
plt.title('Distribusi Panjang Sequence Kata pada text_gabungan', fontsize=15, fontweight='bold')
plt.xlabel('Jumlah Kata dalam Sequence', fontsize=12)
plt.ylabel('Frekuensi (Jumlah Lowongan)', fontsize=12)
plt.legend(loc='upper right', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)

plt.show()

df['seq_length'].describe()

"""#### Inferens"""



import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, LSTM, Bidirectional, Dense, Dot, Flatten, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping

cv_texts = []
job_texts = []
labels = []

# Data Positif (Cocok = 1) -> pseudo_cv dipasangkan dengan job aslinya
for i in range(len(df)):
    cv_texts.append(df['pseudo_cv'].iloc[i])
    job_texts.append(df['text_gabungan'].iloc[i])
    labels.append(1)

# Data Negatif (Tidak Cocok = 0) -> pseudo_cv dipasangkan dengan job random
# Ini penting agar model LSTM tidak sekadar menebak "1" terus menerus
for i in range(len(df)):
    random_idx = np.random.choice([x for x in range(len(df)) if x != i])
    cv_texts.append(df['pseudo_cv'].iloc[i])
    job_texts.append(df['text_gabungan'].iloc[random_idx])
    labels.append(0)

# Convert ke numpy array
labels = np.array(labels)

MAX_VOCAB = 12000
# masih perlu diteliti lebih lanjut
MAX_LEN = 299

tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token="<OOV>")
# Fit tokenizer ke semua teks (CV + Job)
tokenizer.fit_on_texts(cv_texts + job_texts)

# Convert teks ke sequence angka dan lakukan padding
cv_seq = pad_sequences(tokenizer.texts_to_sequences(cv_texts), maxlen=MAX_LEN, padding='post')
job_seq = pad_sequences(tokenizer.texts_to_sequences(job_texts), maxlen=MAX_LEN, padding='post')

from sklearn.model_selection import train_test_split

X_cv_train, X_cv_test, X_job_train, X_job_test, y_train, y_test = train_test_split(
    cv_seq,
    job_seq,
    labels,
    test_size=0.15,
    random_state=42
)

print(f"Total data Train (termasuk Validation nanti): {len(y_train)}")
print(f"Total data Test murni: {len(y_test)}")

# 3. MEMBANGUN ARSITEKTUR CUSTOM LAYER (Siamese BiLSTM)
embedding_dim = 64

# Input Layers
cv_input = Input(shape=(MAX_LEN,), name="cv_input")
job_input = Input(shape=(MAX_LEN,), name="job_input")

# Embedding Layer (Dibagi / Share weights untuk kedua input)
shared_embedding = Embedding(input_dim=MAX_VOCAB, output_dim=embedding_dim, name="shared_embedding")

# BiLSTM Layer (Dibagi / Share weights untuk kedua input)
shared_bilstm = Bidirectional(LSTM(64, return_sequences=False), name="shared_bilstm")

cv_emb = shared_embedding(cv_input)
job_emb = shared_embedding(job_input)

cv_vector = shared_bilstm(cv_emb)
job_vector = shared_bilstm(job_emb)

# Gabungkan vektor CV dan Job secara bersisian
merged_vector = Concatenate(axis=-1, name="gabungan_vektor")([cv_vector, job_vector])

# Tambahkan sedikit layer Dense (otak tambahan) untuk mempelajari pola gabungan tersebut
dense_layer = Dense(32, activation='relu')(merged_vector)

# Output final menggunakan Sigmoid agar nilainya terkurung di 0.0 sampai 1.0
output_layer = Dense(1, activation='sigmoid', name="prediksi_final")(dense_layer)

# Bungkus menjadi model
model = Model(inputs=[cv_input, job_input], outputs=output_layer)

# 2. PERBAIKAN LOSS FUNCTION
model.compile(
    optimizer='adam',
    loss='binary_crossentropy', # <-- Ganti ke sini
    metrics=['accuracy', 'mae'] # Bisa pantau akurasi sekaligus MAE
)

import tensorflow as tf

class JobRecommendationCallback(tf.keras.callbacks.Callback):
    def __init__(self):
        super().__init__()
        self.best_val_accuracy = 0

    def on_train_begin(self, logs=None):
        print("\n=== Training Sistem Rekomendasi Lowongan Dimulai ===")

    def on_epoch_end(self, epoch, logs=None):
        train_acc = logs.get("accuracy")
        val_acc = logs.get("val_accuracy")
        train_loss = logs.get("loss")
        val_loss = logs.get("val_loss")

        print(
            f"\nEpoch {epoch+1}"
            f" | Train Acc: {train_acc:.4f}"
            f" | Val Acc: {val_acc:.4f}"
            f" | Train Loss: {train_loss:.4f}"
            f" | Val Loss: {val_loss:.4f}"
        )

        if val_acc > self.best_val_accuracy:
            self.best_val_accuracy = val_acc
            self.model.save("model_hasil/model_terbaik.keras")

            print(
                f"Model terbaik baru ditemukan "
                f"(val_accuracy={val_acc:.4f})"
            )

        if (train_acc - val_acc) > 0.10:
            print(
                "Indikasi overfitting: "
                "akurasi training jauh lebih tinggi daripada validasi."
            )

    def on_train_end(self, logs=None):
        print("\n=== Training Selesai ===")
        print(
            f"Best Validation Accuracy: "
            f"{self.best_val_accuracy:.4f}"
        )

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

custom_callback = JobRecommendationCallback()

history = model.fit(
    x=[X_cv_train, X_job_train],
    y=y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    callbacks=[
        early_stop,
        custom_callback
    ]
)

import matplotlib.pyplot as plt

# Mengatur ukuran kanvas grafik
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# --- 1. Grafik Pergerakan Loss ---
ax1.plot(history.history['loss'], label='Train Loss', color='blue', linewidth=2)
ax1.plot(history.history['val_loss'], label='Validation Loss', color='orange', linewidth=2, linestyle='--')
ax1.set_title('Pergerakan Loss (Tingkat Kesalahan)', fontsize=14)
ax1.set_xlabel('Epoch', fontsize=12)
ax1.set_ylabel('Loss (Binary Crossentropy)', fontsize=12)
ax1.legend(loc='upper right')
ax1.grid(True, linestyle=':', alpha=0.7)

# --- 2. Grafik Pergerakan Akurasi ---
ax2.plot(history.history['accuracy'], label='Train Accuracy', color='green', linewidth=2)
ax2.plot(history.history['val_accuracy'], label='Validation Accuracy', color='red', linewidth=2, linestyle='--')
ax2.set_title('Pergerakan Akurasi', fontsize=14)
ax2.set_xlabel('Epoch', fontsize=12)
ax2.set_ylabel('Accuracy', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, linestyle=':', alpha=0.7)

# Menampilkan grafik
plt.tight_layout()
plt.show()

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Lakukan prediksi menggunakan data testing
print("Sedang melakukan prediksi pada data testing...")
y_pred_prob = model.predict([X_cv_test, X_job_test])

# 2. Ubah probabilitas menjadi label kelas (0 atau 1) dengan threshold 0.5
# Jika probabilitas > 0.5, maka True (1), jika tidak maka False (0)
y_pred_classes = (y_pred_prob > 0.5).astype(int).flatten()

# 3. Tampilkan Classification Report
print("\n" + "="*40)
print("          CLASSIFICATION REPORT")
print("="*40)
print(classification_report(y_test, y_pred_classes, target_names=['Tidak Cocok (0)', 'Cocok (1)']))

# 4. (Opsional) Tampilkan Confusion Matrix agar lebih visual
cm = confusion_matrix(y_test, y_pred_classes)

plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Prediksi: Tidak Cocok', 'Prediksi: Cocok'],
            yticklabels=['Fakta: Tidak Cocok', 'Fakta: Cocok'])
plt.title('Confusion Matrix pada Data Uji', fontsize=14)
plt.show()

# Menghitung kemiripan (Dot Product sering dipakai untuk mengukur similarity di neural network)
# similarity = Dot(axes=1, normalize=True, name="cosine_similarity")([cv_vector, job_vector])

# # Gabungkan menjadi satu model
# model = Model(inputs=[cv_input, job_input], outputs=similarity)

# model.compile(optimizer='adam', loss='mse', metrics=['mae'])
# model.summary()



#

import pickle

# Tentukan path penyimpanan di Google Drive kamu
# Menggunakan folder yang sama dengan tempat dataset kamu berada

# save_path = '/content/drive/MyDrive/Dataset_codingcamp_loker/'
save_path = './model_hasil/'

# 1. Menyimpan Model Keras
# Menggunakan format .keras yang merupakan standar terbaru dan terefisien dari TensorFlow
model.save(save_path + 'model_rekomendasi_3.keras')

# 2. Menyimpan Tokenizer menggunakan Pickle
with open(save_path + 'tokenizer_loker3.pkl', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

# print("Model dan Tokenizer berhasil disimpan dengan aman di Google Drive!")

# print("\n=== Evaluasi pada Data Test Murni ===")
# eval_results = model.evaluate(x=[X_cv_test, X_job_test], y=y_test)

# print(f"Loss pada Data Test: {eval_results[0]:.4f}")
# print(f"MAE pada Data Test: {eval_results[1]:.4f}")

# contoh pesudo cv
print("Contoh Pseudo CV untuk User:")
print(df['pseudo_cv'][0])

import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Asumsi:
# 1. 'model' sudah di-load atau masih ada di memori.
# 2. 'tokenizer' sudah di-load.
# 3. 'df_raw' adalah dataframe aslimu yang berisi semua lowongan.

# 1. Teks CV dari User (Bisa didapat dari input form)
text_cv_user = "Information Technology and Services kategori: System Analyst pendidikan: bachelor degree tipe: FULL_TIME skills: SQL, Business Analysis, Relational Databases, System Analysis, Analytical Skills, SDLC "

# 2. Siapkan semua teks lowongan kerja dari database (menggunakan text_gabungan)
semua_teks_lowongan = df['text_gabungan'].tolist()
jumlah_lowongan = len(semua_teks_lowongan)

# 3. Gandakan teks CV user agar jumlahnya sama dengan jumlah lowongan
# Ini menciptakan pasangan (CV User, Job 1), (CV User, Job 2), dst...
teks_cv_digandakan = [text_cv_user] * jumlah_lowongan

# 4. Tokenisasi dan Padding
seq_cv_infer = pad_sequences(tokenizer.texts_to_sequences(teks_cv_digandakan), maxlen=MAX_LEN, padding='post')
seq_job_infer = pad_sequences(tokenizer.texts_to_sequences(semua_teks_lowongan), maxlen=MAX_LEN, padding='post')

# 5. Lakukan Prediksi (Mencari skor kecocokan untuk semua pasangan)
print("Sedang mencocokkan CV dengan semua lowongan...")
prediksi_model = model.predict([seq_cv_infer, seq_job_infer])
prediksi_model = prediksi_model.flatten() # Ratakan ke 1D agar mudah digabung dengan skor TF-IDF

tfidf = TfidfVectorizer(max_features=MAX_VOCAB, ngram_range=(1,2))
judul_lowongan = df['Judul'].tolist() + ["Backend Developer"]
tfidf_matrix = tfidf.fit_transform(judul_lowongan)

prediksi_tfidf = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1]).flatten()

skor_prediksi = (0.5 * prediksi_model) + (0.5 * prediksi_tfidf) # Gabungkan skor model dan TF-IDF dengan bobot 50:50

# 6. Mengurutkan hasil dari skor tertinggi ke terendah
# argsort mengembalikan index. '[::-1]' digunakan untuk membalik urutan agar yang terbesar di awal.
index_terbaik = np.argsort(skor_prediksi)[::-1]

# 7. Tampilkan Top 5 Rekomendasi Teratas
top_n = 10
print(f"\n=== TOP {top_n} REKOMENDASI LOWONGAN KERJA ===")

for i in range(top_n):
    idx = index_terbaik[i]
    skor = skor_prediksi[idx]

    # Hanya tampilkan jika skornya di atas threshold (misal > 0.5)
    if skor > 0.5:
        print(f"\nRekomendasi #{i+1} (Skor Kecocokan: {skor:.4f})")
        # Mengambil data dari raw dataframe berdasarkan index
        print(f"Judul    : {df.loc[idx, 'Judul']}")
        print(f"Perusahaan: {df.loc[idx, 'Industri']}") # Ganti dengan kolom yang sesuai
        print(f"Lokasi   : {df.loc[idx, 'Kota']}")
    else:
        print(f"\nRekomendasi #{i+1}: Tidak ada lagi lowongan yang dianggap cocok (Skor < 0.5)")
        break

